chore: apply Prettier auto-formatting to codebase (#17)

diff --git a/.github/workflows/connector-tests.yml b/.github/workflows/connector-tests.yml
--- a/.github/workflows/connector-tests.yml
+++ b/.github/workflows/connector-tests.yml
@@ -51,7 +51,6 @@ jobs:
       vector-db-based: ${{ steps.changes.outputs.vector-db-based }}
       sql: ${{ steps.changes.outputs.sql }}
 
-
     #   # The Connector CI Tests is a status check emitted by airbyte-ci
     #   # We make it pass once we have determined that there are no changes to the connectors
     #   - name: "Skip Connectors CI tests"
@@ -76,7 +75,7 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 360 # 6 hours
     strategy:
-      fail-fast: true  # Save resources by aborting if one connector fails
+      fail-fast: true # Save resources by aborting if one connector fails
       matrix:
         include:
           - connector: source-shopify
@@ -98,9 +97,9 @@ jobs:
         id: no_changes
         if: ${{ matrix.cdk_extra != 'n/a' && needs.cdk_changes.outputs[matrix.cdk_extra] == 'false' }}
         run: |
-            echo "Aborting job as specified extra not changed: ${{matrix.cdk_extra}} = ${{ needs.cdk_changes.outputs[matrix.cdk_extra] }}"
-            echo "status=cancelled" >> $GITHUB_OUTPUT
-            exit 1
+          echo "Aborting job as specified extra not changed: ${{matrix.cdk_extra}} = ${{ needs.cdk_changes.outputs[matrix.cdk_extra] }}"
+          echo "status=cancelled" >> $GITHUB_OUTPUT
+          exit 1
         continue-on-error: true
       # Get the monorepo so we can test the connectors
       - name: Checkout Airbyte Monorepo
